### ISSUE TITLE
please release new version

### ISSUE THREAD

**Issue by qt06** [gexgd0419/NaturalVoiceSAPIAdapter#15]
Since May 10th, there are many changes, but the releases page has no the new version.

**Comment by amirsol81** [comment]
@gexgd0419 Not to put any pressure on you to have the updated engine released, but is there an easy way to try your latest changes? Since this needs an installation to work, I assume we can't simply copy/paste the altered files, but I might be mistaken. Thanks.

**Comment by gexgd0419** [comment]
@amirsol81 This project is made using Visual Studio 2022. C++ and ATL is required.

The NaturalVoiceSAPIAdapter.dll can be installed by just using `regsvr32` (with administrator's privilege). The installer does just that, and provides a user interface for changing some settings stored in the registry.

Also, Visual Studio will automatically try to register the DLL file after each successful build.

**Comment by amirsol81** [comment]
@gexgd0419 Thanks for your explanation. It's, of course, complicated for a non-developer like me, so I'd rather wait for the next release.

**Comment by qt06** [comment]
下面这几个项目不论我选什么 c++ 版本和 c 版本都无法正常编译： Installer, SpeechSDKPatcher, SpeechSDKShim 
他们都有类似下面的错误提示：
E0135. 命名空间 "std" 没有成员 "make_unique"
C2039. "unique_ptr": 不是 "std" 的成员
C7568. 假定的函数模板“unique_ptr”后面缺少参数列表
请教这几个项目应该如何配置呢？谢谢！

**Comment by gexgd0419** [comment]
@qt06 The Installer project is not finished, and the submitted code on GitHub is not ready for compiling yet.

Many of my projects use the `Visual Studio 2017 - Windows XP (v141_xp)` toolset to be compatible with Windows XP.

You should choose to install `C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]` (`对 VS 2017 (v141) 工具的 C++ Windows XP 支持 [已弃用]`) in the Visual Studio Installer.

SpeechSDKPatcher and SpeechSDKShim cannot be built because of the incorrect NuGet package settings. But they also exist as a [standalone project](https://github.com/gexgd0419/AzureSpeechSDKShim/). You can try building using the VS solution inside the AzureSpeechSDKShim folder.

However, the main NaturalVoiceSAPIAdapter project should be able to compile. It uses the newest toolset and C++ version, and uses [YY-Thunks](https://github.com/Chuyu-Team/YY-Thunks) to be compatible with Windows XP. The installer isn't really needed, as you can use `regsvr32` to register the DLL.

**Comment by qt06** [comment]
ok, thank you.

**Comment by gexgd0419** [comment]
A new version [v0.2](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2) has been released!

**Comment by amirsol81** [comment]
@gexgd0419 Thanks!Message ID: 
***@***.***>
