### ISSUE TITLE
New options available in Windows 11

### ISSUE THREAD

**Issue by warrenkc** [gexgd0419/NaturalVoiceSAPIAdapter#21]
I hope this is not a bother. Just noticed that I can use the natural voices for narrator  in Windows 11 version 23H2. 
Hopefully this helps others.
I don't see other languages available yet.

https://www.microsoft.com/store/productId/9MT3MDCCXWRT?ocid=pdpshare
![Screenshot 2024-09-18 164346](https://github.com/user-attachments/assets/adb64bab-d613-46a9-ada3-dc73d062540f)
![Screenshot 2024-09-18 164414](https://github.com/user-attachments/assets/ebaadcb9-60e8-40af-b61c-adfdcc4ed535)
![Screenshot 2024-09-18 170527](https://github.com/user-attachments/assets/2d7dcace-84fb-45f1-b70a-525c3f3e92e2)

**Comment by gexgd0419** [comment]
Yes, these natural voices are originally only for Narrator and nothing else, and they are not accessible to third-party apps, unlike the SAPI5 and OneCore voices such as "Microsoft Zira (Desktop)" which can be used by any third-party app but also sounds more robotic.

This project makes the Narrator-exclusive natural voices accessible through SAPI5, a standard speech system interface that has been built into Windows since Windows XP, and are used by many third-party apps that need text-to-speech support.

I also made [a list](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/wiki/Narrator-natural-voice-download-links) for the currently available Narrator natural voices, so that you can download and use those voices on Windows 10 or even Windows 7. Feel free to let me know when the list needs to be updated.

**Comment by warrenkc** [comment]
Thank you so much for the awesome work.
