### ISSUE TITLE
Large pause between sentences

### ISSUE THREAD

**Issue by SergeyShevelevAlexandrovich** [gexgd0419/NaturalVoiceSAPIAdapter#28]
In the program balabolka ( in others not tested ), pauses between sentences are very long, setting the duration of the pause in the setting balabolka do not change anything.

**Comment by gexgd0419** [comment]
Balabolka sends each sentence to the TTS engine one at a time. The next sentence will not be sent before the current sentence finishes speaking.

This isn't an issue if you are using offline voices, because offline voices has little delay. But online voices can have delay of a few hundred milliseconds, depending on your Internet connection. Also, online voices usually add a ~200ms silence period after each sentence. So the pause duration between sentences that you perceive = silence period duration + connection delay.

If we cannot change how Balabolka sends text to TTS engines, the connection delay between each sentence cannot be avoid. However, in the current version, there is a hidden feature that removes the trailing silence period to shorten the delay.

Open registry editor, go to `HKEY_CURRENT_USER\Software\NaturalVoiceSAPIAdapter`, add a DWORD value called `EnableOnlineDelayOptimization` and set its value to 1. After that, you can check if the pause duration becomes better.

If this feature is effective, I will put it in the installer UI in a future release.

**Comment by SergeyShevelevAlexandrovich** [comment]
> Balabolka sends each sentence to the TTS engine one at a time. The next sentence will not be sent before the current sentence finishes speaking.
> 
> This isn't an issue if you are using offline voices, because offline voices has little delay. But online voices can have delay of a few hundred milliseconds, depending on your Internet connection. Also, online voices usually add a ~200ms silence period after each sentence. So the pause duration between sentences that you perceive = silence period duration + connection delay.
> 
> If we cannot change how Balabolka sends text to TTS engines, the connection delay between each sentence cannot be avoid. However, in the current version, there is a hidden feature that removes the trailing silence period to shorten the delay.
> 
> Open registry editor, go to `HKEY_CURRENT_USER\Software\NaturalVoiceSAPIAdapter`, add a DWORD value called `EnableOnlineDelayOptimization` and set its value to 1. After that, you can check if the pause duration becomes better.
> 
> If this feature is effective, I will put it in the installer UI in a future release.

I noticed a difference, not much, but still got better, so can add it to the app, it won't be worse.

**Comment by SergeyShevelevAlexandrovich** [comment]
The delay was medium at first ( possible internet instability ), now it's become minimal, so yes, it did help.
