### ISSUE TITLE
Register as a OneCore voice as well

### ISSUE THREAD

**Issue by SnowSquire** [gexgd0419/NaturalVoiceSAPIAdapter#4]
Some programs no longer use the sapi5. for example brave browser, or Calibre by default. i'm not quite sure what the api they use is called, but i believe it is winspeech

**Comment by SnowSquire** [comment]
https://github..com/kovidgoyal/calibre/blob/master/src/calibre/utils/windows/winspeech.py

**Comment by gexgd0419** [comment]
Yes, currently Chromium browsers and UWP apps only support OneCore voices, not SAPI 5 voices.

(But also thanks to that, Microsoft Edge doesn't show a duplicated item for each online voice, when using this engine with Edge voices enabled.)

However, here's what Microsoft says in the [documentation about OneCore SpeechSynthesizer](https://learn.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer?view=winrt-22621):

> Only **Microsoft-signed** voices installed on the system can be used to generate speech.

There's no way this engine could be signed by Microsoft...

Also I haven't found documentation about how to implement your own  OneCore TTS engine, so I guess that it's impossible.

**Comment by maxoptimus** [comment]
In calibre latests on windows you can set like old sys in settings and got sapi5 list there; and it will show in default reader read option; but still calibre have bad wraper maybe because use pyton piper....

use icebookreaderpro is best - with sentences option in speech; then demagog but need more config;
